<?php

function webcam_snapshot_demo_menu() {
  return array(
    'webcam_snapshot/demo' => array(
      'title' => 'Webcam Snapshot Demonstration',
      'description' => 'Form API Field Demonstation.',
      'file' => 'webcam_snapshot_demo.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('webcam_snapshot_demo_form'),
      'access arguments' => array('access webcam snapshot demonstration'),
    ),
  );
}

function webcam_snapshot_perm() {
  return array('access webcam snapshot demonstration');
}
